name: places
description: A new Flutter project.
organization: Evdokimov-sailing


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  - res:

  - res/fonts:
    
  dart_code_metrics: ^4.16.0

  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0
  flutter_svg: ^1.1.0


flutter:


  uses-material-design: true

  assets:
    - asset: res/fonts/Roboto-Light.ttf

  fonts: 
    - family: Roboto
      fonts: 
        - asset: res/fonts/Roboto-Light.ttf



  